// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { listEvents, listOrgs, listTasks, type Options, refreshToken, signIn, signOut, signUp, tryExecuteTask } from '../sdk.gen';
import type { ListEventsData, ListEventsResponse, ListOrgsData, ListOrgsResponse, ListTasksData, ListTasksResponse, RefreshTokenData, RefreshTokenResponse, SignInData, SignInResponse, SignOutData, SignUpData, SignUpResponse, TryExecuteTaskData } from '../types.gen';

/**
 * Sign in user
 *
 * Authenticate user and return access token
 */
export const signInMutation = (options?: Partial<Options<SignInData>>): UseMutationOptions<SignInResponse, DefaultError, Options<SignInData>> => {
    const mutationOptions: UseMutationOptions<SignInResponse, DefaultError, Options<SignInData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await signIn({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Sign up user
 *
 * Create a new user and return credentials
 */
export const signUpMutation = (options?: Partial<Options<SignUpData>>): UseMutationOptions<SignUpResponse, DefaultError, Options<SignUpData>> => {
    const mutationOptions: UseMutationOptions<SignUpResponse, DefaultError, Options<SignUpData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await signUp({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Sign out user
 *
 * Sign out user and invalidate all tokens
 */
export const signOutMutation = (options?: Partial<Options<SignOutData>>): UseMutationOptions<unknown, DefaultError, Options<SignOutData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<SignOutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await signOut({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Refresh access token
 *
 * Get a new access token using a refresh token
 */
export const refreshTokenMutation = (options?: Partial<Options<RefreshTokenData>>): UseMutationOptions<RefreshTokenResponse, DefaultError, Options<RefreshTokenData>> => {
    const mutationOptions: UseMutationOptions<RefreshTokenResponse, DefaultError, Options<RefreshTokenData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await refreshToken({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const listTasksQueryKey = (options?: Options<ListTasksData>) => createQueryKey('listTasks', options);

/**
 * Get all tasks
 *
 * Get all tasks
 */
export const listTasksOptions = (options?: Options<ListTasksData>) => queryOptions<ListTasksResponse, DefaultError, ListTasksResponse, ReturnType<typeof listTasksQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listTasks({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listTasksQueryKey(options)
});

export const listEventsQueryKey = (options?: Options<ListEventsData>) => createQueryKey('listEvents', options);

/**
 * Get all events
 *
 * Get all events
 */
export const listEventsOptions = (options?: Options<ListEventsData>) => queryOptions<ListEventsResponse, DefaultError, ListEventsResponse, ReturnType<typeof listEventsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listEvents({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listEventsQueryKey(options)
});

export const listOrgsQueryKey = (options?: Options<ListOrgsData>) => createQueryKey('listOrgs', options);

/**
 * Get all organizations of which the user is a member
 *
 * Get all organizations of which the user is a member
 */
export const listOrgsOptions = (options?: Options<ListOrgsData>) => queryOptions<ListOrgsResponse, DefaultError, ListOrgsResponse, ReturnType<typeof listOrgsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listOrgs({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listOrgsQueryKey(options)
});

/**
 * Try to execute a task
 *
 * Try to execute a task
 */
export const tryExecuteTaskMutation = (options?: Partial<Options<TryExecuteTaskData>>): UseMutationOptions<unknown, DefaultError, Options<TryExecuteTaskData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<TryExecuteTaskData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await tryExecuteTask({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
