// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { ListEventsData, ListEventsResponses, ListOrgsData, ListOrgsResponses, ListTasksData, ListTasksResponses, RefreshTokenData, RefreshTokenErrors, RefreshTokenResponses, SignInData, SignInErrors, SignInResponses, SignOutData, SignOutResponses, SignUpData, SignUpErrors, SignUpResponses, TryExecuteTaskData, TryExecuteTaskErrors, TryExecuteTaskResponses } from './types.gen';
import { zListEventsData, zListOrgsData, zListTasksData, zRefreshTokenData, zSignInData, zSignOutData, zSignUpData, zTryExecuteTaskData } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Sign in user
 *
 * Authenticate user and return access token
 */
export const signIn = <ThrowOnError extends boolean = false>(options: Options<SignInData, ThrowOnError>) => (options.client ?? client).post<SignInResponses, SignInErrors, ThrowOnError>({
    requestValidator: async (data) => await zSignInData.parseAsync(data),
    url: '/auth/sign-in',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Sign up user
 *
 * Create a new user and return credentials
 */
export const signUp = <ThrowOnError extends boolean = false>(options: Options<SignUpData, ThrowOnError>) => (options.client ?? client).post<SignUpResponses, SignUpErrors, ThrowOnError>({
    requestValidator: async (data) => await zSignUpData.parseAsync(data),
    url: '/auth/sign-up',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Sign out user
 *
 * Sign out user and invalidate all tokens
 */
export const signOut = <ThrowOnError extends boolean = false>(options?: Options<SignOutData, ThrowOnError>) => (options?.client ?? client).post<SignOutResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zSignOutData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/sign-out',
    ...options
});

/**
 * Refresh access token
 *
 * Get a new access token using a refresh token
 */
export const refreshToken = <ThrowOnError extends boolean = false>(options: Options<RefreshTokenData, ThrowOnError>) => (options.client ?? client).post<RefreshTokenResponses, RefreshTokenErrors, ThrowOnError>({
    requestValidator: async (data) => await zRefreshTokenData.parseAsync(data),
    url: '/auth/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get all tasks
 *
 * Get all tasks
 */
export const listTasks = <ThrowOnError extends boolean = false>(options?: Options<ListTasksData, ThrowOnError>) => (options?.client ?? client).get<ListTasksResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zListTasksData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tasks',
    ...options
});

/**
 * Get all events
 *
 * Get all events
 */
export const listEvents = <ThrowOnError extends boolean = false>(options?: Options<ListEventsData, ThrowOnError>) => (options?.client ?? client).get<ListEventsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zListEventsData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/events',
    ...options
});

/**
 * Get all organizations of which the user is a member
 *
 * Get all organizations of which the user is a member
 */
export const listOrgs = <ThrowOnError extends boolean = false>(options?: Options<ListOrgsData, ThrowOnError>) => (options?.client ?? client).get<ListOrgsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zListOrgsData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/orgs',
    ...options
});

/**
 * Try to execute a task
 *
 * Try to execute a task
 */
export const tryExecuteTask = <ThrowOnError extends boolean = false>(options: Options<TryExecuteTaskData, ThrowOnError>) => (options.client ?? client).post<TryExecuteTaskResponses, TryExecuteTaskErrors, ThrowOnError>({
    requestValidator: async (data) => await zTryExecuteTaskData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tasks/{taskID}/try-execute',
    ...options
});
