// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type SignInRequest = {
    /**
     * User's name
     */
    name: string;
    /**
     * User's password
     */
    password: string;
};

export type SignUpRequest = {
    /**
     * User's name
     */
    name: string;
    /**
     * User's password
     */
    password: string;
};

export type Credentials = {
    /**
     * JWT access token
     */
    accessToken: string;
    /**
     * JWT refresh token for obtaining new access tokens
     */
    refreshToken: string;
    /**
     * Token type
     */
    tokenType: 'Bearer';
};

export type RefreshTokenRequest = {
    /**
     * Refresh token obtained from sign-in
     */
    refreshToken: string;
};

export type Task = {
    ID: number;
    /**
     * Parent task ID if this task was spawned from another task
     */
    parentTaskId?: number;
    attributes: TaskAttributes;
    spec: TaskSpec;
    status: 'pending' | 'completed' | 'failed' | 'paused' | 'cancelled';
    /**
     * Unique tag of the task
     */
    uniqueTag?: string;
    /**
     * Worker ID that currently owns the task
     */
    workerId?: string;
    startedAt?: string;
    lockedAt?: string;
    createdAt: string;
    updatedAt: string;
    events: Array<'onFailed'>;
    /**
     * The number of times the task has been attempted
     */
    attempts: number;
};

export type TaskSpec = {
    type: string;
    /**
     * The JSONB of the spec of the task
     */
    payload: {
        [key: string]: unknown;
    };
};

export type TaskAttributes = {
    /**
     * Strict priority of the task. Higher number runs first. Zero means normal weighted scheduling.
     */
    priority?: number;
    /**
     * Relative weight of the task within weighted scheduling (normal tasks only).
     */
    weight?: number;
    /**
     * Timeout of the task, a valid go time duration value e.g. 1h, 1d, 1w, 1m
     */
    timeout?: string;
    cronjob?: TaskCronjob;
    retryPolicy?: TaskRetryPolicy;
    labels?: Array<string>;
    /**
     * Serial key for forcing tasks with the same key to run one by one
     */
    serialKey?: string;
    /**
     * Optional serial order within the same serial key (lower runs first)
     */
    serialID?: number;
};

export type TaskRetryPolicy = {
    /**
     * Interval of the retry policy, e.g. 1h, 1d, 1w, 1m
     */
    interval: string;
    /**
     * Maximum number of attempts to retry the task, -1 means infinite retries
     */
    maxAttempts: number;
};

export type TaskCronjob = {
    cronExpression: string;
};

export type Event = {
    ID: number;
    spec: EventSpec;
    createdAt: string;
};

export type EventSpec = {
    type: 'TaskError' | 'TaskCompleted';
    taskError?: EventTaskError;
    taskCompleted?: EventTaskCompleted;
};

export type EventTaskError = {
    taskID: number;
    error: string;
};

export type EventTaskCompleted = {
    taskID: number;
};

export type Org = {
    ID: number;
    name: string;
    createdAt: string;
    updatedAt: string;
};

export type SignInData = {
    body: SignInRequest;
    path?: never;
    query?: never;
    url: '/auth/sign-in';
};

export type SignInErrors = {
    /**
     * Invalid credentials
     */
    401: unknown;
};

export type SignInResponses = {
    /**
     * Successfully authenticated
     */
    200: Credentials;
};

export type SignInResponse = SignInResponses[keyof SignInResponses];

export type SignUpData = {
    body: SignUpRequest;
    path?: never;
    query?: never;
    url: '/auth/sign-up';
};

export type SignUpErrors = {
    /**
     * Username already exists
     */
    409: unknown;
};

export type SignUpResponses = {
    /**
     * Successfully signed up
     */
    201: Credentials;
};

export type SignUpResponse = SignUpResponses[keyof SignUpResponses];

export type SignOutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/sign-out';
};

export type SignOutResponses = {
    /**
     * Successfully signed out
     */
    200: unknown;
};

export type RefreshTokenData = {
    body: RefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshTokenErrors = {
    /**
     * Invalid or expired refresh token
     */
    401: unknown;
};

export type RefreshTokenResponses = {
    /**
     * Successfully refreshed token
     */
    200: Credentials;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type ListTasksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tasks';
};

export type ListTasksResponses = {
    /**
     * Successfully retrieved tasks
     */
    200: Array<Task>;
};

export type ListTasksResponse = ListTasksResponses[keyof ListTasksResponses];

export type ListEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/events';
};

export type ListEventsResponses = {
    /**
     * Successfully retrieved events
     */
    200: Array<Event>;
};

export type ListEventsResponse = ListEventsResponses[keyof ListEventsResponses];

export type ListOrgsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/orgs';
};

export type ListOrgsResponses = {
    /**
     * Successfully retrieved organizations
     */
    200: Array<Org>;
};

export type ListOrgsResponse = ListOrgsResponses[keyof ListOrgsResponses];

export type TryExecuteTaskData = {
    body?: never;
    path: {
        taskID: number;
    };
    query?: never;
    url: '/tasks/{taskID}/try-execute';
};

export type TryExecuteTaskErrors = {
    /**
     * Task not found
     */
    404: unknown;
};

export type TryExecuteTaskResponses = {
    /**
     * Successfully tried to execute the task
     */
    200: unknown;
};
