// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zSignInRequest = z.object({
    name: z.string(),
    password: z.string()
});

export const zSignUpRequest = z.object({
    name: z.string(),
    password: z.string()
});

export const zCredentials = z.object({
    accessToken: z.string(),
    refreshToken: z.string(),
    tokenType: z.enum(['Bearer'])
});

export const zRefreshTokenRequest = z.object({
    refreshToken: z.string()
});

export const zTaskSpec = z.object({
    type: z.string(),
    payload: z.record(z.string(), z.unknown())
});

export const zTaskRetryPolicy = z.object({
    interval: z.string(),
    maxAttempts: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zTaskCronjob = z.object({
    cronExpression: z.string()
});

export const zTaskAttributes = z.object({
    priority: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    weight: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    timeout: z.string().optional(),
    cronjob: zTaskCronjob.optional(),
    retryPolicy: zTaskRetryPolicy.optional(),
    labels: z.array(z.string()).optional(),
    serialKey: z.string().optional(),
    serialID: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
});

export const zTask = z.object({
    ID: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    parentTaskId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
    attributes: zTaskAttributes,
    spec: zTaskSpec,
    status: z.enum([
        'pending',
        'completed',
        'failed',
        'paused',
        'cancelled'
    ]),
    uniqueTag: z.string().optional(),
    workerId: z.string().optional(),
    startedAt: z.iso.datetime().optional(),
    lockedAt: z.iso.datetime().optional(),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime(),
    events: z.array(z.enum(['onFailed'])),
    attempts: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zEventTaskError = z.object({
    taskID: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    error: z.string()
});

export const zEventTaskCompleted = z.object({
    taskID: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zEventSpec = z.object({
    type: z.enum(['TaskError', 'TaskCompleted']),
    taskError: zEventTaskError.optional(),
    taskCompleted: zEventTaskCompleted.optional()
});

export const zEvent = z.object({
    ID: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    spec: zEventSpec,
    createdAt: z.iso.datetime()
});

export const zOrg = z.object({
    ID: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    name: z.string(),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime()
});

export const zSignInData = z.object({
    body: zSignInRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zSignUpData = z.object({
    body: zSignUpRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zSignOutData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zRefreshTokenData = z.object({
    body: zRefreshTokenRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zListTasksData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zListEventsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zListOrgsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zTryExecuteTaskData = z.object({
    body: z.never().optional(),
    path: z.object({
        taskID: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    }),
    query: z.never().optional()
});
