// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createMemo, deleteAttachment, deleteMemo, downloadAttachment, getAttachment, getMemo, linkAttachment, listAttachmentsByResource, listMemoBacklinks, listMemos, listTags, type Options, unlinkAttachment, updateMemo, uploadAttachment } from '../sdk.gen';
import type { CreateMemoData, CreateMemoResponse, DeleteAttachmentData, DeleteAttachmentResponse, DeleteMemoData, DeleteMemoResponse, DownloadAttachmentData, DownloadAttachmentResponse, GetAttachmentData, GetAttachmentResponse, GetMemoData, GetMemoResponse, LinkAttachmentData, LinkAttachmentResponse, ListAttachmentsByResourceData, ListAttachmentsByResourceResponse, ListMemoBacklinksData, ListMemoBacklinksResponse, ListMemosData, ListMemosResponse, ListTagsData, ListTagsResponse, UnlinkAttachmentData, UnlinkAttachmentResponse, UpdateMemoData, UpdateMemoResponse, UploadAttachmentData, UploadAttachmentResponse } from '../types.gen';

/**
 * Upload attachment
 */
export const uploadAttachmentMutation = (options?: Partial<Options<UploadAttachmentData>>): UseMutationOptions<UploadAttachmentResponse, DefaultError, Options<UploadAttachmentData>> => {
    const mutationOptions: UseMutationOptions<UploadAttachmentResponse, DefaultError, Options<UploadAttachmentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await uploadAttachment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete attachment
 */
export const deleteAttachmentMutation = (options?: Partial<Options<DeleteAttachmentData>>): UseMutationOptions<DeleteAttachmentResponse, DefaultError, Options<DeleteAttachmentData>> => {
    const mutationOptions: UseMutationOptions<DeleteAttachmentResponse, DefaultError, Options<DeleteAttachmentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteAttachment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getAttachmentQueryKey = (options: Options<GetAttachmentData>) => createQueryKey('getAttachment', options);

/**
 * Get attachment metadata
 */
export const getAttachmentOptions = (options: Options<GetAttachmentData>) => queryOptions<GetAttachmentResponse, DefaultError, GetAttachmentResponse, ReturnType<typeof getAttachmentQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAttachment({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAttachmentQueryKey(options)
});

export const downloadAttachmentQueryKey = (options: Options<DownloadAttachmentData>) => createQueryKey('downloadAttachment', options);

/**
 * Download attachment content
 */
export const downloadAttachmentOptions = (options: Options<DownloadAttachmentData>) => queryOptions<DownloadAttachmentResponse, DefaultError, DownloadAttachmentResponse, ReturnType<typeof downloadAttachmentQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await downloadAttachment({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: downloadAttachmentQueryKey(options)
});

/**
 * Unlink attachment from a resource
 */
export const unlinkAttachmentMutation = (options?: Partial<Options<UnlinkAttachmentData>>): UseMutationOptions<UnlinkAttachmentResponse, DefaultError, Options<UnlinkAttachmentData>> => {
    const mutationOptions: UseMutationOptions<UnlinkAttachmentResponse, DefaultError, Options<UnlinkAttachmentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await unlinkAttachment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Link attachment to a resource
 */
export const linkAttachmentMutation = (options?: Partial<Options<LinkAttachmentData>>): UseMutationOptions<LinkAttachmentResponse, DefaultError, Options<LinkAttachmentData>> => {
    const mutationOptions: UseMutationOptions<LinkAttachmentResponse, DefaultError, Options<LinkAttachmentData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await linkAttachment({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listMemosQueryKey = (options?: Options<ListMemosData>) => createQueryKey('listMemos', options);

/**
 * List memos for current user
 */
export const listMemosOptions = (options?: Options<ListMemosData>) => queryOptions<ListMemosResponse, DefaultError, ListMemosResponse, ReturnType<typeof listMemosQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listMemos({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listMemosQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const listMemosInfiniteQueryKey = (options?: Options<ListMemosData>): QueryKey<Options<ListMemosData>> => createQueryKey('listMemos', options, true);

/**
 * List memos for current user
 */
export const listMemosInfiniteOptions = (options?: Options<ListMemosData>) => infiniteQueryOptions<ListMemosResponse, DefaultError, InfiniteData<ListMemosResponse>, QueryKey<Options<ListMemosData>>, number | Pick<QueryKey<Options<ListMemosData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ListMemosData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                offset: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listMemos({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listMemosInfiniteQueryKey(options)
});

/**
 * Create a new memo
 */
export const createMemoMutation = (options?: Partial<Options<CreateMemoData>>): UseMutationOptions<CreateMemoResponse, DefaultError, Options<CreateMemoData>> => {
    const mutationOptions: UseMutationOptions<CreateMemoResponse, DefaultError, Options<CreateMemoData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createMemo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a memo
 */
export const deleteMemoMutation = (options?: Partial<Options<DeleteMemoData>>): UseMutationOptions<DeleteMemoResponse, DefaultError, Options<DeleteMemoData>> => {
    const mutationOptions: UseMutationOptions<DeleteMemoResponse, DefaultError, Options<DeleteMemoData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteMemo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getMemoQueryKey = (options: Options<GetMemoData>) => createQueryKey('getMemo', options);

/**
 * Get memo by ID
 */
export const getMemoOptions = (options: Options<GetMemoData>) => queryOptions<GetMemoResponse, DefaultError, GetMemoResponse, ReturnType<typeof getMemoQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getMemo({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getMemoQueryKey(options)
});

/**
 * Update a memo
 */
export const updateMemoMutation = (options?: Partial<Options<UpdateMemoData>>): UseMutationOptions<UpdateMemoResponse, DefaultError, Options<UpdateMemoData>> => {
    const mutationOptions: UseMutationOptions<UpdateMemoResponse, DefaultError, Options<UpdateMemoData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateMemo({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listMemoBacklinksQueryKey = (options: Options<ListMemoBacklinksData>) => createQueryKey('listMemoBacklinks', options);

/**
 * List backlinks for a memo
 */
export const listMemoBacklinksOptions = (options: Options<ListMemoBacklinksData>) => queryOptions<ListMemoBacklinksResponse, DefaultError, ListMemoBacklinksResponse, ReturnType<typeof listMemoBacklinksQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listMemoBacklinks({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listMemoBacklinksQueryKey(options)
});

export const listAttachmentsByResourceQueryKey = (options: Options<ListAttachmentsByResourceData>) => createQueryKey('listAttachmentsByResource', options);

/**
 * List attachments by resource
 */
export const listAttachmentsByResourceOptions = (options: Options<ListAttachmentsByResourceData>) => queryOptions<ListAttachmentsByResourceResponse, DefaultError, ListAttachmentsByResourceResponse, ReturnType<typeof listAttachmentsByResourceQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listAttachmentsByResource({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listAttachmentsByResourceQueryKey(options)
});

export const listTagsQueryKey = (options?: Options<ListTagsData>) => createQueryKey('listTags', options);

/**
 * List tags for current user
 */
export const listTagsOptions = (options?: Options<ListTagsData>) => queryOptions<ListTagsResponse, DefaultError, ListTagsResponse, ReturnType<typeof listTagsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listTags({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listTagsQueryKey(options)
});

export const listTagsInfiniteQueryKey = (options?: Options<ListTagsData>): QueryKey<Options<ListTagsData>> => createQueryKey('listTags', options, true);

/**
 * List tags for current user
 */
export const listTagsInfiniteOptions = (options?: Options<ListTagsData>) => infiniteQueryOptions<ListTagsResponse, DefaultError, InfiniteData<ListTagsResponse>, QueryKey<Options<ListTagsData>>, number | Pick<QueryKey<Options<ListTagsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ListTagsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                offset: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listTags({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listTagsInfiniteQueryKey(options)
});
