// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateMemoData, CreateMemoErrors, CreateMemoResponses, DeleteAttachmentData, DeleteAttachmentErrors, DeleteAttachmentResponses, DeleteMemoData, DeleteMemoErrors, DeleteMemoResponses, DownloadAttachmentData, DownloadAttachmentErrors, DownloadAttachmentResponses, GetAttachmentData, GetAttachmentErrors, GetAttachmentResponses, GetMemoData, GetMemoErrors, GetMemoResponses, LinkAttachmentData, LinkAttachmentErrors, LinkAttachmentResponses, ListAttachmentsByResourceData, ListAttachmentsByResourceResponses, ListMemoBacklinksData, ListMemoBacklinksErrors, ListMemoBacklinksResponses, ListMemosData, ListMemosResponses, ListTagsData, ListTagsResponses, UnlinkAttachmentData, UnlinkAttachmentErrors, UnlinkAttachmentResponses, UpdateMemoData, UpdateMemoErrors, UpdateMemoResponses, UploadAttachmentData, UploadAttachmentResponses } from './types.gen';
import { zCreateMemoData, zDeleteAttachmentData, zDeleteMemoData, zDownloadAttachmentData, zGetAttachmentData, zGetMemoData, zLinkAttachmentData, zListAttachmentsByResourceData, zListMemoBacklinksData, zListMemosData, zListTagsData, zUnlinkAttachmentData, zUpdateMemoData, zUploadAttachmentData } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Upload attachment
 */
export const uploadAttachment = <ThrowOnError extends boolean = false>(options: Options<UploadAttachmentData, ThrowOnError>) => (options.client ?? client).post<UploadAttachmentResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    requestValidator: async (data) => await zUploadAttachmentData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/attachments',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Delete attachment
 */
export const deleteAttachment = <ThrowOnError extends boolean = false>(options: Options<DeleteAttachmentData, ThrowOnError>) => (options.client ?? client).delete<DeleteAttachmentResponses, DeleteAttachmentErrors, ThrowOnError>({
    requestValidator: async (data) => await zDeleteAttachmentData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/attachments/{id}',
    ...options
});

/**
 * Get attachment metadata
 */
export const getAttachment = <ThrowOnError extends boolean = false>(options: Options<GetAttachmentData, ThrowOnError>) => (options.client ?? client).get<GetAttachmentResponses, GetAttachmentErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetAttachmentData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/attachments/{id}',
    ...options
});

/**
 * Download attachment content
 */
export const downloadAttachment = <ThrowOnError extends boolean = false>(options: Options<DownloadAttachmentData, ThrowOnError>) => (options.client ?? client).get<DownloadAttachmentResponses, DownloadAttachmentErrors, ThrowOnError>({
    requestValidator: async (data) => await zDownloadAttachmentData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/attachments/{id}/content',
    ...options
});

/**
 * Unlink attachment from a resource
 */
export const unlinkAttachment = <ThrowOnError extends boolean = false>(options: Options<UnlinkAttachmentData, ThrowOnError>) => (options.client ?? client).delete<UnlinkAttachmentResponses, UnlinkAttachmentErrors, ThrowOnError>({
    requestValidator: async (data) => await zUnlinkAttachmentData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/attachments/{id}/links',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Link attachment to a resource
 */
export const linkAttachment = <ThrowOnError extends boolean = false>(options: Options<LinkAttachmentData, ThrowOnError>) => (options.client ?? client).post<LinkAttachmentResponses, LinkAttachmentErrors, ThrowOnError>({
    requestValidator: async (data) => await zLinkAttachmentData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/attachments/{id}/links',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List memos for current user
 */
export const listMemos = <ThrowOnError extends boolean = false>(options?: Options<ListMemosData, ThrowOnError>) => (options?.client ?? client).get<ListMemosResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zListMemosData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/memos',
    ...options
});

/**
 * Create a new memo
 */
export const createMemo = <ThrowOnError extends boolean = false>(options: Options<CreateMemoData, ThrowOnError>) => (options.client ?? client).post<CreateMemoResponses, CreateMemoErrors, ThrowOnError>({
    requestValidator: async (data) => await zCreateMemoData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/memos',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a memo
 */
export const deleteMemo = <ThrowOnError extends boolean = false>(options: Options<DeleteMemoData, ThrowOnError>) => (options.client ?? client).delete<DeleteMemoResponses, DeleteMemoErrors, ThrowOnError>({
    requestValidator: async (data) => await zDeleteMemoData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/memos/{id}',
    ...options
});

/**
 * Get memo by ID
 */
export const getMemo = <ThrowOnError extends boolean = false>(options: Options<GetMemoData, ThrowOnError>) => (options.client ?? client).get<GetMemoResponses, GetMemoErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetMemoData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/memos/{id}',
    ...options
});

/**
 * Update a memo
 */
export const updateMemo = <ThrowOnError extends boolean = false>(options: Options<UpdateMemoData, ThrowOnError>) => (options.client ?? client).patch<UpdateMemoResponses, UpdateMemoErrors, ThrowOnError>({
    requestValidator: async (data) => await zUpdateMemoData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/memos/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List backlinks for a memo
 */
export const listMemoBacklinks = <ThrowOnError extends boolean = false>(options: Options<ListMemoBacklinksData, ThrowOnError>) => (options.client ?? client).get<ListMemoBacklinksResponses, ListMemoBacklinksErrors, ThrowOnError>({
    requestValidator: async (data) => await zListMemoBacklinksData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/memos/{id}/backlinks',
    ...options
});

/**
 * List attachments by resource
 */
export const listAttachmentsByResource = <ThrowOnError extends boolean = false>(options: Options<ListAttachmentsByResourceData, ThrowOnError>) => (options.client ?? client).get<ListAttachmentsByResourceResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zListAttachmentsByResourceData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/resources/{resourceType}/{resourceId}/attachments',
    ...options
});

/**
 * List tags for current user
 */
export const listTags = <ThrowOnError extends boolean = false>(options?: Options<ListTagsData, ThrowOnError>) => (options?.client ?? client).get<ListTagsResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zListTagsData.parseAsync(data),
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tags',
    ...options
});
