// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:2910/api/v1' | `${string}://${string}/api/v1` | (string & {});
};

export type Attachment = {
    contentType: string;
    createdAt: string;
    downloadUrl: string;
    filename: string;
    id: string;
    sizeBytes: number;
};

export type Counter = {
    count: number;
};

export type CreateMemoRequest = {
    content: string;
};

export type CreateTodoRequest = {
    title: string;
};

export type LinkAttachmentRequest = {
    resourceId: string;
    resourceType: string;
};

export type Memo = {
    archivedAt?: string | null;
    content: string;
    createdAt: string;
    excerpt: string;
    id: string;
    references: Array<string>;
    state: MemoState;
    tags: Array<string>;
    updatedAt: string;
};

export type MemoState = 'active' | 'archived';

export type MemoSummary = {
    archivedAt?: string | null;
    createdAt: string;
    excerpt: string;
    id: string;
    state: MemoState;
    tags: Array<string>;
    updatedAt: string;
};

export type TagSummary = {
    count: number;
    name: string;
};

export type TodoItem = {
    bucket: 'later' | 'week' | 'today';
    createdAt: string;
    description: string;
    done: boolean;
    id: string;
    title: string;
};

export type UpdateMemoRequest = {
    content?: string;
    state?: MemoState;
};

export type UpdateTodoRequest = {
    bucket?: 'later' | 'week' | 'today';
    description?: string;
    done?: boolean;
    title?: string;
};

export type UploadAttachmentData = {
    body: {
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/attachments';
};

export type UploadAttachmentResponses = {
    /**
     * Attachment uploaded
     */
    201: Attachment;
};

export type UploadAttachmentResponse = UploadAttachmentResponses[keyof UploadAttachmentResponses];

export type DeleteAttachmentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/attachments/{id}';
};

export type DeleteAttachmentErrors = {
    /**
     * Attachment not found
     */
    404: unknown;
};

export type DeleteAttachmentResponses = {
    /**
     * Attachment deleted
     */
    204: void;
};

export type DeleteAttachmentResponse = DeleteAttachmentResponses[keyof DeleteAttachmentResponses];

export type GetAttachmentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/attachments/{id}';
};

export type GetAttachmentErrors = {
    /**
     * Attachment not found
     */
    404: unknown;
};

export type GetAttachmentResponses = {
    /**
     * Attachment metadata
     */
    200: Attachment;
};

export type GetAttachmentResponse = GetAttachmentResponses[keyof GetAttachmentResponses];

export type DownloadAttachmentData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/attachments/{id}/content';
};

export type DownloadAttachmentErrors = {
    /**
     * Attachment not found
     */
    404: unknown;
};

export type DownloadAttachmentResponses = {
    /**
     * Attachment content
     */
    200: Blob | File;
};

export type DownloadAttachmentResponse = DownloadAttachmentResponses[keyof DownloadAttachmentResponses];

export type UnlinkAttachmentData = {
    body: LinkAttachmentRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/attachments/{id}/links';
};

export type UnlinkAttachmentErrors = {
    /**
     * Attachment not found
     */
    404: unknown;
};

export type UnlinkAttachmentResponses = {
    /**
     * Attachment unlinked
     */
    204: void;
};

export type UnlinkAttachmentResponse = UnlinkAttachmentResponses[keyof UnlinkAttachmentResponses];

export type LinkAttachmentData = {
    body: LinkAttachmentRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/attachments/{id}/links';
};

export type LinkAttachmentErrors = {
    /**
     * Attachment not found
     */
    404: unknown;
};

export type LinkAttachmentResponses = {
    /**
     * Attachment linked
     */
    204: void;
};

export type LinkAttachmentResponse = LinkAttachmentResponses[keyof LinkAttachmentResponses];

export type ListMemosData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        tag?: string;
        state?: MemoState;
        limit?: number;
        offset?: number;
    };
    url: '/memos';
};

export type ListMemosResponses = {
    /**
     * Memo list
     */
    200: Array<MemoSummary>;
};

export type ListMemosResponse = ListMemosResponses[keyof ListMemosResponses];

export type CreateMemoData = {
    body: CreateMemoRequest;
    path?: never;
    query?: never;
    url: '/memos';
};

export type CreateMemoErrors = {
    /**
     * Invalid memo references
     */
    422: unknown;
};

export type CreateMemoResponses = {
    /**
     * Created memo
     */
    201: Memo;
};

export type CreateMemoResponse = CreateMemoResponses[keyof CreateMemoResponses];

export type DeleteMemoData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/memos/{id}';
};

export type DeleteMemoErrors = {
    /**
     * Memo not found
     */
    404: unknown;
};

export type DeleteMemoResponses = {
    /**
     * Memo deleted
     */
    204: void;
};

export type DeleteMemoResponse = DeleteMemoResponses[keyof DeleteMemoResponses];

export type GetMemoData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/memos/{id}';
};

export type GetMemoErrors = {
    /**
     * Memo not found
     */
    404: unknown;
};

export type GetMemoResponses = {
    /**
     * Memo details
     */
    200: Memo;
};

export type GetMemoResponse = GetMemoResponses[keyof GetMemoResponses];

export type UpdateMemoData = {
    body: UpdateMemoRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/memos/{id}';
};

export type UpdateMemoErrors = {
    /**
     * Memo not found
     */
    404: unknown;
    /**
     * Invalid memo references
     */
    422: unknown;
};

export type UpdateMemoResponses = {
    /**
     * Updated memo
     */
    200: Memo;
};

export type UpdateMemoResponse = UpdateMemoResponses[keyof UpdateMemoResponses];

export type ListMemoBacklinksData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/memos/{id}/backlinks';
};

export type ListMemoBacklinksErrors = {
    /**
     * Memo not found
     */
    404: unknown;
};

export type ListMemoBacklinksResponses = {
    /**
     * Backlink list
     */
    200: Array<MemoSummary>;
};

export type ListMemoBacklinksResponse = ListMemoBacklinksResponses[keyof ListMemoBacklinksResponses];

export type ListAttachmentsByResourceData = {
    body?: never;
    path: {
        resourceType: string;
        resourceId: string;
    };
    query?: never;
    url: '/resources/{resourceType}/{resourceId}/attachments';
};

export type ListAttachmentsByResourceResponses = {
    /**
     * Attachment list
     */
    200: Array<Attachment>;
};

export type ListAttachmentsByResourceResponse = ListAttachmentsByResourceResponses[keyof ListAttachmentsByResourceResponses];

export type ListTagsData = {
    body?: never;
    path?: never;
    query?: {
        q?: string;
        limit?: number;
        offset?: number;
    };
    url: '/tags';
};

export type ListTagsResponses = {
    /**
     * Tag list
     */
    200: Array<TagSummary>;
};

export type ListTagsResponse = ListTagsResponses[keyof ListTagsResponses];
