// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zAttachment = z.object({
    contentType: z.string(),
    createdAt: z.iso.datetime(),
    downloadUrl: z.string(),
    filename: z.string(),
    id: z.uuid(),
    sizeBytes: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zCounter = z.object({
    count: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export const zCreateTodoRequest = z.object({
    title: z.string()
});

export const zLinkAttachmentRequest = z.object({
    resourceId: z.uuid(),
    resourceType: z.string()
});

export const zMemoContent = z.unknown();

export const zCreateMemoRequest = z.object({
    content: zMemoContent,
    excerpt: z.string(),
    plainText: z.string(),
    references: z.array(z.uuid()),
    tags: z.array(z.string())
});

export const zMemoState = z.enum(['active', 'archived']);

export const zMemo = z.object({
    archivedAt: z.iso.datetime().nullish(),
    content: zMemoContent,
    createdAt: z.iso.datetime(),
    excerpt: z.string(),
    id: z.uuid(),
    plainText: z.string(),
    references: z.array(z.uuid()),
    state: zMemoState,
    tags: z.array(z.string()),
    updatedAt: z.iso.datetime()
});

export const zMemoSummary = z.object({
    archivedAt: z.iso.datetime().nullish(),
    createdAt: z.iso.datetime(),
    excerpt: z.string(),
    id: z.uuid(),
    plainText: z.string(),
    state: zMemoState,
    tags: z.array(z.string()),
    updatedAt: z.iso.datetime()
});

export const zTagSummary = z.object({
    count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    name: z.string()
});

export const zTodoItem = z.object({
    bucket: z.enum([
        'later',
        'week',
        'today'
    ]),
    createdAt: z.iso.datetime(),
    description: z.string(),
    done: z.boolean(),
    id: z.uuid(),
    title: z.string()
});

export const zUpdateMemoRequest = z.object({
    content: zMemoContent,
    excerpt: z.string(),
    plainText: z.string(),
    references: z.array(z.uuid()),
    state: zMemoState.optional(),
    tags: z.array(z.string())
});

export const zUpdateTodoRequest = z.object({
    bucket: z.enum([
        'later',
        'week',
        'today'
    ]).optional(),
    description: z.string().optional(),
    done: z.boolean().optional(),
    title: z.string().optional()
});

export const zUploadAttachmentData = z.object({
    body: z.object({
        file: z.string()
    }),
    path: z.never().optional(),
    query: z.never().optional()
});

export const zDeleteAttachmentData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.uuid()
    }),
    query: z.never().optional()
});

export const zGetAttachmentData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.uuid()
    }),
    query: z.never().optional()
});

export const zDownloadAttachmentData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.uuid()
    }),
    query: z.never().optional()
});

export const zUnlinkAttachmentData = z.object({
    body: zLinkAttachmentRequest,
    path: z.object({
        id: z.uuid()
    }),
    query: z.never().optional()
});

export const zLinkAttachmentData = z.object({
    body: zLinkAttachmentRequest,
    path: z.object({
        id: z.uuid()
    }),
    query: z.never().optional()
});

export const zListMemosData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        q: z.string().optional(),
        tag: z.string().optional(),
        state: zMemoState.optional(),
        limit: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional().default(50),
        offset: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional().default(0)
    }).optional()
});

export const zCreateMemoData = z.object({
    body: zCreateMemoRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

export const zDeleteMemoData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.uuid()
    }),
    query: z.never().optional()
});

export const zGetMemoData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.uuid()
    }),
    query: z.never().optional()
});

export const zUpdateMemoData = z.object({
    body: zUpdateMemoRequest,
    path: z.object({
        id: z.uuid()
    }),
    query: z.never().optional()
});

export const zListMemoBacklinksData = z.object({
    body: z.never().optional(),
    path: z.object({
        id: z.uuid()
    }),
    query: z.never().optional()
});

export const zListAttachmentsByResourceData = z.object({
    body: z.never().optional(),
    path: z.object({
        resourceType: z.string(),
        resourceId: z.uuid()
    }),
    query: z.never().optional()
});

export const zListTagsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        q: z.string().optional(),
        limit: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional().default(50),
        offset: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional().default(0)
    }).optional()
});
